-- Isolated read-API database fixture; storage definitions match the existing migrations.
create table if not exists public.lottery_draws (
  id bigint generated by default as identity primary key,
  lottery text not null check (lottery in ('今彩539', '天天樂', '六合彩', '大樂透')),
  period text not null,
  draw_date date,
  numbers jsonb not null check (jsonb_typeof(numbers) = 'array'),
  sorted_numbers jsonb not null check (jsonb_typeof(sorted_numbers) = 'array'),
  draw_order_numbers jsonb check (draw_order_numbers is null or jsonb_typeof(draw_order_numbers) = 'array'),
  source_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lottery, period)
);

create table if not exists public.matrix_analysis_runs (
  id uuid primary key default gen_random_uuid(),
  lottery text not null check (lottery in ('今彩539', '天天樂', '六合彩', '大樂透')),
  draw_period text not null,
  analysis_version text not null,
  phase text not null check (phase in ('explore', 'tianyan', 'tiangong', 'status', 'complete')),
  cursor integer not null default 0 check (cursor >= 0),
  total integer not null default 0 check (total >= 0),
  status text not null check (status in ('running', 'complete', 'failed')),
  started_at timestamptz not null,
  completed_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lottery, draw_period, analysis_version)
);

create table if not exists public.matrix_analysis_artifacts (
  id uuid primary key default gen_random_uuid(),
  lottery text not null check (lottery in ('今彩539', '天天樂', '六合彩', '大樂透')),
  draw_period text not null,
  analysis_version text not null,
  kind text not null check (kind in ('explore', 'tianyan', 'tiangong', 'status')),
  payload jsonb not null,
  completed_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (lottery, draw_period, analysis_version, kind),
  foreign key (lottery, draw_period, analysis_version)
    references public.matrix_analysis_runs (lottery, draw_period, analysis_version)
    on delete cascade
);

create index if not exists matrix_analysis_runs_completed_lookup_idx
  on public.matrix_analysis_runs (lottery, draw_period, completed_at desc)
  where status = 'complete';

create index if not exists matrix_analysis_artifacts_expiry_idx
  on public.matrix_analysis_artifacts (expires_at);

alter table public.lottery_draws enable row level security;
alter table public.matrix_analysis_runs enable row level security;
alter table public.matrix_analysis_artifacts enable row level security;

revoke all on table public.lottery_draws from anon, authenticated;
revoke all on table public.matrix_analysis_runs from anon, authenticated;
revoke all on table public.matrix_analysis_artifacts from anon, authenticated;

grant select, insert, update, delete on table public.lottery_draws to service_role;
grant select, insert, update, delete on table public.matrix_analysis_runs to service_role;
grant select, insert, update, delete on table public.matrix_analysis_artifacts to service_role;
grant usage, select on sequence public.lottery_draws_id_seq to service_role;


create table if not exists public.matrix_explore_results (
  lottery text not null check (lottery in ('今彩539', '天天樂', '六合彩', '大樂透')),
  draw_period text not null,
  analysis_version text not null,
  item_id text not null,
  number text not null,
  locked_position integer not null check (locked_position > 0),
  prediction_distance integer not null check (prediction_distance > 0),
  consecutive text not null,
  highest_streak integer not null check (highest_streak > 0),
  prediction_numbers jsonb not null check (pg_catalog.jsonb_typeof(prediction_numbers) = 'array'),
  algorithm_type text not null check (algorithm_type in ('加減', '合值', '拖牌')),
  number_order text not null check (number_order in ('依號碼由小到大排序', '依實際開獎順序排序')),
  rule_count integer not null check (rule_count in (1, 2)),
  locked_source_index integer not null check (locked_source_index between 0 and 12),
  locked_source_period text not null,
  reference_offset integer,
  reference_position integer,
  item jsonb not null check (pg_catalog.jsonb_typeof(item) = 'object'),
  validation jsonb not null check (pg_catalog.jsonb_typeof(validation) = 'object'),
  expires_at timestamptz not null,
  created_at timestamptz not null default pg_catalog.now(),
  primary key (lottery, draw_period, analysis_version, item_id),
  foreign key (lottery, draw_period, analysis_version)
    references public.matrix_analysis_runs (lottery, draw_period, analysis_version)
    on delete cascade
);


create table public.matrix_tianheng_results (
  lottery text not null check (lottery in ('今彩539','天天樂','六合彩','大樂透')),
  draw_period text not null,
  analysis_version text not null,
  item_id text not null,
  first_number text not null,
  first_locked_position integer not null check (first_locked_position > 0),
  second_number text not null,
  second_locked_position integer not null check (second_locked_position > first_locked_position),
  prediction_distance integer not null check (prediction_distance > 0),
  consecutive text not null,
  highest_streak integer not null check (highest_streak > 0),
  prediction_numbers jsonb not null check (jsonb_typeof(prediction_numbers) = 'array'),
  algorithm_type text not null check (algorithm_type in ('加減','合值','拖牌')),
  number_order text not null check (number_order in ('依號碼由小到大排序','依實際開獎順序排序')),
  rule_count integer not null check (rule_count in (1,2)),
  explore_range text not null check (explore_range in ('標準範圍','完整範圍')),
  locked_source_index integer not null check (locked_source_index between 0 and 12),
  locked_source_period text not null,
  reference_offset integer,
  reference_position integer,
  item jsonb not null check (jsonb_typeof(item) = 'object'),
  validation jsonb not null check (jsonb_typeof(validation) = 'object'),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  primary key (lottery, draw_period, analysis_version, item_id),
  foreign key (lottery, draw_period, analysis_version)
    references public.matrix_analysis_runs(lottery, draw_period, analysis_version)
    on delete cascade
);


alter table public.lottery_draws add column result_status text not null default 'confirmed';
alter table public.matrix_explore_results add column explore_range text not null default '標準範圍';
alter table public.matrix_analysis_artifacts drop constraint matrix_analysis_artifacts_kind_check;
alter table public.matrix_analysis_artifacts add constraint matrix_analysis_artifacts_kind_check check (kind in ('explore','tianheng','tianyan','tiangong','status'));

CREATE OR REPLACE FUNCTION private.matrix_artifact_payload(p_kind text, p_lottery text, p_draw_period text, p_analysis_version text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_payload jsonb;
  v_items jsonb;
  v_validations jsonb;
begin
  select artifact.payload into v_payload
  from public.matrix_analysis_artifacts as artifact
  where artifact.kind = p_kind
    and artifact.lottery = p_lottery
    and artifact.draw_period = p_draw_period
    and artifact.analysis_version = p_analysis_version
  limit 1;

  if v_payload is null then return null; end if;
  if coalesce(v_payload->>'storage', '') <> 'chunks' then return v_payload; end if;

  select coalesce(pg_catalog.jsonb_agg(item order by chunk.chunk_index), '[]'::jsonb)
    into v_items
  from public.matrix_analysis_artifact_chunks as chunk
  cross join lateral pg_catalog.jsonb_array_elements(
    coalesce(chunk.payload->'items', '[]'::jsonb)
  ) as item
  where chunk.kind = p_kind
    and chunk.lottery = p_lottery
    and chunk.draw_period = p_draw_period
    and chunk.analysis_version = p_analysis_version;

  select coalesce(pg_catalog.jsonb_object_agg(pair.key, pair.value), '{}'::jsonb)
    into v_validations
  from public.matrix_analysis_artifact_chunks as chunk
  cross join lateral pg_catalog.jsonb_each(
    coalesce(chunk.payload->'validationById', '{}'::jsonb)
  ) as pair
  where chunk.kind = p_kind
    and chunk.lottery = p_lottery
    and chunk.draw_period = p_draw_period
    and chunk.analysis_version = p_analysis_version;

  return pg_catalog.jsonb_build_object(
    'lottery', p_lottery,
    'drawPeriod', p_draw_period,
    'items', v_items,
    'validationById', v_validations
  );
end;
$function$
;
