create table if not exists public.lottery_draws (
  id bigint generated by default as identity primary key,
  lottery text not null check (lottery in ('今彩539', '天天樂', '六合彩', '大樂透')),
  period text not null,
  draw_date date,
  numbers jsonb not null check (jsonb_typeof(numbers) = 'array'),
  sorted_numbers jsonb not null check (jsonb_typeof(sorted_numbers) = 'array'),
  draw_order_numbers jsonb check (draw_order_numbers is null or jsonb_typeof(draw_order_numbers) = 'array'),
  source_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lottery, period)
);

create table if not exists public.matrix_analysis_runs (
  id uuid primary key default gen_random_uuid(),
  lottery text not null check (lottery in ('今彩539', '天天樂', '六合彩', '大樂透')),
  draw_period text not null,
  analysis_version text not null,
  phase text not null check (phase in ('explore', 'tianyan', 'tiangong', 'status', 'complete')),
  cursor integer not null default 0 check (cursor >= 0),
  total integer not null default 0 check (total >= 0),
  status text not null check (status in ('running', 'complete', 'failed')),
  started_at timestamptz not null,
  completed_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lottery, draw_period, analysis_version)
);

create table if not exists public.matrix_analysis_artifacts (
  id uuid primary key default gen_random_uuid(),
  lottery text not null check (lottery in ('今彩539', '天天樂', '六合彩', '大樂透')),
  draw_period text not null,
  analysis_version text not null,
  kind text not null check (kind in ('explore', 'tianyan', 'tiangong', 'status')),
  payload jsonb not null,
  completed_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (lottery, draw_period, analysis_version, kind),
  foreign key (lottery, draw_period, analysis_version)
    references public.matrix_analysis_runs (lottery, draw_period, analysis_version)
    on delete cascade
);

create index if not exists matrix_analysis_runs_completed_lookup_idx
  on public.matrix_analysis_runs (lottery, draw_period, completed_at desc)
  where status = 'complete';

create index if not exists matrix_analysis_artifacts_expiry_idx
  on public.matrix_analysis_artifacts (expires_at);

alter table public.lottery_draws enable row level security;
alter table public.matrix_analysis_runs enable row level security;
alter table public.matrix_analysis_artifacts enable row level security;

revoke all on table public.lottery_draws from anon, authenticated;
revoke all on table public.matrix_analysis_runs from anon, authenticated;
revoke all on table public.matrix_analysis_artifacts from anon, authenticated;

grant select, insert, update, delete on table public.lottery_draws to service_role;
grant select, insert, update, delete on table public.matrix_analysis_runs to service_role;
grant select, insert, update, delete on table public.matrix_analysis_artifacts to service_role;
grant usage, select on sequence public.lottery_draws_id_seq to service_role;
