create table if not exists private.line_pwa_handoff_diagnostics (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  request_id text not null check (request_id ~ '^[a-zA-Z0-9-]{1,80}$'),
  events jsonb not null check (
    jsonb_typeof(events) = 'array'
    and jsonb_array_length(events) between 1 and 40
    and octet_length(events::text) <= 24576
  ),
  created_at timestamptz not null default now(),
  unique (auth_user_id, request_id)
);

revoke all on table private.line_pwa_handoff_diagnostics from public, anon, authenticated;
revoke all on sequence private.line_pwa_handoff_diagnostics_id_seq from public, anon, authenticated;

create or replace function public.member_line_pwa_diagnostics_submit(p_events jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_event jsonb;
  v_request_id text;
  v_code text;
  v_error_name text;
  v_worker_build text;
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if jsonb_typeof(p_events) <> 'array'
    or jsonb_array_length(p_events) not between 1 and 40
    or octet_length(p_events::text) > 24576 then
    raise exception 'DIAGNOSTICS_INVALID' using errcode = '22023';
  end if;

  for v_event in select value from jsonb_array_elements(p_events)
  loop
    if jsonb_typeof(v_event) <> 'object'
      or exists (
        select 1 from jsonb_object_keys(v_event) as key
        where key not in ('at', 'requestId', 'code', 'errorName', 'workerBuild', 'elapsedMs', 'candidateCount')
      ) then
      raise exception 'DIAGNOSTICS_INVALID' using errcode = '22023';
    end if;

    v_request_id := v_event ->> 'requestId';
    v_code := v_event ->> 'code';
    v_error_name := v_event ->> 'errorName';
    v_worker_build := v_event ->> 'workerBuild';
    if v_request_id is null or v_request_id !~ '^[a-zA-Z0-9-]{1,80}$'
      or v_code is null or v_code not in (
        'CALLBACK_RECEIVED', 'WORKER_READY_TIMEOUT', 'WORKER_READY_FAILED',
        'WORKER_UNAVAILABLE', 'WORKER_REQUEST_POST_FAILED', 'WORKER_RESPONSE_TIMEOUT',
        'WORKER_LEGACY_SUCCESS', 'WORKER_LEGACY_FAILURE', 'WORKER_RESULT_UNKNOWN',
        'CALLBACK_INVALID', 'PWA_LOOKUP_STARTED', 'PWA_CLIENT_STALE',
        'PWA_CLIENT_LOOKUP_FAILED', 'PWA_CLIENT_NOT_FOUND', 'PWA_PROBE_STARTED',
        'PWA_PROBE_TIMEOUT', 'PWA_CLIENT_FOUND', 'PWA_FOCUS_STARTED',
        'PWA_FOCUS_RESOLVED', 'PWA_FOCUS_REJECTED', 'PWA_NAVIGATION_STARTED',
        'PWA_NAVIGATION_REJECTED', 'PWA_NAVIGATION_EMPTY', 'PWA_CALLBACK_POST_FAILED',
        'HANDOFF_DISPATCHED'
      )
      or (v_event ? 'at' and jsonb_typeof(v_event -> 'at') <> 'number')
      or (v_event ? 'elapsedMs' and jsonb_typeof(v_event -> 'elapsedMs') <> 'number')
      or (v_event ? 'candidateCount' and jsonb_typeof(v_event -> 'candidateCount') <> 'number')
      or (v_error_name is not null and v_error_name not in (
        'InvalidAccessError', 'InvalidStateError', 'SecurityError', 'NotAllowedError',
        'AbortError', 'NotFoundError', 'TypeError', 'Error', 'UnknownError'
      ))
      or (v_worker_build is not null and v_worker_build !~ '^matrix-pwa-shell-([a-f0-9]{16}|__BUILD_ID__)$') then
      raise exception 'DIAGNOSTICS_INVALID' using errcode = '22023';
    end if;
  end loop;

  v_request_id := p_events -> -1 ->> 'requestId';
  insert into private.line_pwa_handoff_diagnostics (auth_user_id, request_id, events)
  values (v_uid, v_request_id, p_events)
  on conflict (auth_user_id, request_id) do update
    set events = excluded.events,
        created_at = now();

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.member_line_pwa_diagnostics_submit(jsonb) from public, anon, authenticated, service_role;
grant execute on function public.member_line_pwa_diagnostics_submit(jsonb) to authenticated;
