begin;

create table if not exists public.matrix_analysis_artifact_chunks (
  id bigint generated by default as identity primary key,
  lottery text not null check (lottery in ('今彩539', '天天樂', '六合彩', '大樂透')),
  draw_period text not null,
  analysis_version text not null,
  kind text not null check (kind in ('explore', 'tianyan', 'tiangong', 'status')),
  chunk_index integer not null check (chunk_index >= 0),
  cursor_start integer not null check (cursor_start >= 0),
  cursor_end integer not null check (cursor_end > cursor_start),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (lottery, draw_period, analysis_version, kind, chunk_index),
  foreign key (lottery, draw_period, analysis_version)
    references public.matrix_analysis_runs (lottery, draw_period, analysis_version)
    on delete cascade
);

create index if not exists matrix_analysis_artifact_chunks_expiry_idx
  on public.matrix_analysis_artifact_chunks (expires_at);

alter table public.matrix_analysis_artifact_chunks enable row level security;
revoke all on table public.matrix_analysis_artifact_chunks from anon, authenticated;
grant select, insert, update, delete on table public.matrix_analysis_artifact_chunks to service_role;
grant usage, select on sequence public.matrix_analysis_artifact_chunks_id_seq to service_role;

delete from public.matrix_analysis_artifacts artifact
using public.matrix_analysis_runs run
where artifact.lottery = run.lottery
  and artifact.draw_period = run.draw_period
  and artifact.analysis_version = run.analysis_version
  and artifact.kind = 'explore'
  and run.status <> 'complete';

update public.matrix_analysis_runs
set phase = 'explore',
    cursor = 0,
    total = 0,
    status = 'running',
    completed_at = null,
    error = null,
    updated_at = now()
where status <> 'complete';

commit;
